services:
  - type: web
    name: krisha-elo
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
